name: server_workflows.yml
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Apt update
        run: |
          sudo apt update
          sudo apt install -y cmake

      - name: Install Conan
        run: pip3 install conan

      - name: Configure Conan Packages
        run: |
          conan profile detect --force
          conan install . --build=missing

      - name: CMake Configure
        run: cmake -S . -B build/Release -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

      - name: CMake Build
        run: cmake --build build/Release

      - name: Run tests
        run: ./build/Release/server_tests_bin