name: server_workflows.yml
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install required apt packages
        run: |
          sudo apt update
          sudo apt install -y cmake lcov make

      - name: Setup Conan Client
        uses: conan-io/setup-conan@v1
        with:
          conan_audit_token: ${{ secrets.CONAN_AUDIT_TOKEN }}

      - name: Install Conan dependencies
        run: conan build . --build=missing

      - name: Run GTest
        run: ctest --test-dir build/Release

      - name: Coverage
        shell: bash
        run: |
          cd build/Release
          make coverage

      - name: Coveralls
        if: ${{ github.actor != 'nektos/act' }}
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: build/Release/CMakeFiles/server_library.dir/src/coverage.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
