name: server_workflows.yml
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install required apt packages
        run: |
          sudo apt update
          sudo apt install -y cmake lcov make

      - name: Setup Conan Client
        uses: conan-io/setup-conan@v1
        with:
          conan_audit_token: ${{ secrets.CONAN_AUDIT_TOKEN }}

      - name: Install Conan dependencies
        run: conan build . --build=missing -s build_type=Debug

      - name: Run GTest
        run: ctest --test-dir build/Debug

      - name: Coverage
        shell: bash
        run: |
          cd build/Release
          make coverage

      - name: Report Code Coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: build/Debug/CMakeFiles/server_library.dir/src/coverage.info
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}